### ISSUE TITLE
sorry,I follow your tutorial,but I got a error.

### ISSUE THREAD

**Issue by HadXu** [flyyufelix/cnn_finetune#14]
```
Traceback (most recent call last):
  File "C:/Users/hadxu/PycharmProjects/Quant_implement/deep-learning/fine-tuning/VGG16_tuning.py", line 106, in <module>
    model = vgg16_model(img_rows, img_cols, channel, num_classes)
  File "C:/Users/hadxu/PycharmProjects/Quant_implement/deep-learning/fine-tuning/VGG16_tuning.py", line 39, in vgg16_model
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\keras\models.py", line 466, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\keras\engine\topology.py", line 585, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\keras\layers\pooling.py", line 154, in call
    data_format=self.data_format)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\keras\layers\pooling.py", line 217, in _pooling_function
    pool_mode='max')
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\keras\backend\tensorflow_backend.py", line 3245, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1821, in max_pool
    name=name)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1638, in _max_pool
    data_format=data_format, name=name)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\framework\ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\framework\ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\framework\ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "C:\Program Files\Anaconda3\envs\deep-learning\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_2/MaxPool' (op: 'MaxPool') with input shapes: [?,1,112,128].
```

**Comment by huberbuab** [comment]
I actually got the same error. Anybody has any ideas?

**Comment by flyyufelix** [comment]
As you can see from readme, for VGG16, we only provide pre-trained models in Theano format. Hence, in vgg16.py, use of theano backend is assumed. You have to switch to theano backend in order to run vgg16.py (by editing ~.keras/keras.json).

**Comment by HadXu** [comment]
OK,thank you!
