### ISSUE TITLE
"negative dimension" constructing VGG16

### ISSUE THREAD

**Issue by Noahyt** [flyyufelix/cnn_finetune#21]
When running the VGG16 code I get this error: 

`Traceback (most recent call last):
  File "/Users/noah/Documents/TensorFlow/10_2_week/cnn_finetune-master/vgg16.py", line 105, in <module>
    model = vgg16_model(img_rows, img_cols, channel, num_classes)
  File "/Users/noah/Documents/TensorFlow/10_2_week/cnn_finetune-master/vgg16.py", line 34, in vgg16_model
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))
  File "/Users/noah/anaconda/lib/python3.6/site-packages/keras/models.py", line 475, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/noah/anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/noah/anaconda/lib/python3.6/site-packages/keras/layers/pooling.py", line 154, in call
    data_format=self.data_format)
  File "/Users/noah/anaconda/lib/python3.6/site-packages/keras/layers/pooling.py", line 217, in _pooling_function
    pool_mode='max')
  File "/Users/noah/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3386, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1772, in max_pool
    name=name)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1605, in _max_pool
    data_format=data_format, name=name)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1861, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "/Users/noah/Documents/TensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_2/MaxPool' (op: 'MaxPool') with input shapes: [?,1,112,128].
`

**Comment by Noahyt** [comment]
I believe input shape should be formatted as (w,h,c), i.e, 
`input_shape=(img_rows, img_cols,channel)`
