### ISSUE TITLE
Negative dimension size when reproducing the result using Inception_v3

### ISSUE THREAD

**Issue by wangjksjtu** [flyyufelix/cnn_finetune#22]
I have run some models such as densenet169 and they work well. Thank you for this helpful work!!!

However, when I try to run inception_v3 model, this error occurs and there seem some bugs in the framework of inception_v3.  The error log is as follows:
```
Traceback (most recent call last):
  File "inception_v3_tmp.py", line 238, in <module>
    model = inception_v3_model(img_rows, img_cols, channel, num_classes)
  File "inception_v3_tmp.py", line 56, in inception_v3_model
    x = conv2d_bn(x, 32, 3, 3, border_mode='valid')
  File "inception_v3_tmp.py", line 31, in conv2d_bn
    name=conv_name)(x)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3161, in conv2d
    data_format='NHWC')
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/wangjk/.virtualenvs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,1,149,32], [3,3,32,32].

```

**Comment by flyyufelix** [comment]
Inception_v3 pre-trained model is running on Theano backend. Make sure you change your keras backend to Theano:

In keras.json file:

```
"image_dim_ordering": "th",
"backend": "theano"
```

**Comment by wangjksjtu** [comment]
Get it, thank you so much!
