### ISSUE TITLE
ValueError: Error when checking target

### ISSUE THREAD

**Issue by hiroshiperera** [flyyufelix/cnn_finetune#37]
Hi I got the following error when trying to fine-tune the code for ResNet50.

Warning (from warnings module):
  File "C:\CT_SCAN_IMAGE_SET\resnet_50\dbs2017\fyufelix_cnn_finetune_4.py", line 210
    validation_data=(X_valid, Y_valid),
UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
Traceback (most recent call last):
  File "C:\CT_SCAN_IMAGE_SET\resnet_50\dbs2017\fyufelix_cnn_finetune_4.py", line 210, in <module>
    validation_data=(X_valid, Y_valid),
  File "C:\Research\Python_installation\lib\site-packages\keras\engine\training.py", line 1581, in fit
    batch_size=batch_size)
  File "C:\Research\Python_installation\lib\site-packages\keras\engine\training.py", line 1418, in _standardize_user_data
    exception_prefix='target')
  File "C:\Research\Python_installation\lib\site-packages\keras\engine\training.py", line 141, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected fc10 to have 2 dimensions, but got array with shape (277, 224, 224, 3)

Can someone please let me know that how I can fix this

X_train.shape - (1107,  224, 224, 3)
Y_train.shape - (277,  224, 224 , 3)
X_valid.shape- (1107,)
Y_valid.shape - (277,)

**Comment by camelia-pixel** [comment]
do you find a solution of this problem @hiroshiperera

**Comment by Arwenlearn** [comment]
I meet the same problem, do you know how to solve it?
