### ISSUE TITLE
Issue will running densenet?

### ISSUE THREAD

**Issue by neenu05** [flyyufelix/cnn_finetune#54]

**Comment by neenu05** [comment]
Hi,
I am trying to run the code densenet121.py,  but end up with below error.

G:\cnn_finetune-master>python densenet121.py
Using TensorFlow backend.
2019-01-11 12:56:00.413035: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "densenet121.py", line 224, in <module>
    model = densenet121_model(img_rows=img_rows, img_cols=img_cols, color_type=channel, num_classes=num_classes)
  File "densenet121.py", line 74, in densenet121_model
    x, filters = dense_block(x, stage, nb_layers[block_idx], filters, growth_rate, dropout_rate=dropout_rate, weight_decay=weight_decay)
  File "densenet121.py", line 203, in dense_block
    concat_feat = concatenate([concat_feat, x], mode='concat', concat_axis=concat_axis, name='concat_'+str(stage)+'_'+str(branch))##concat_feat = merge([concat_feat, x], mode='concat', concat_axis=concat_axis, name='concat_'+str(stage)+'_'+str(branch))
  File "C:\Users\Neenu\Anaconda3\lib\site-packages\keras\layers\merge.py", line 649, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "C:\Users\Neenu\Anaconda3\lib\site-packages\keras\layers\merge.py", line 341, in __init__
    super(Concatenate, self).__init__(**kwargs)
  File "C:\Users\Neenu\Anaconda3\lib\site-packages\keras\layers\merge.py", line 21, in __init__
    super(_Merge, self).__init__(**kwargs)
  File "C:\Users\Neenu\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 128, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'mode')

Im using keras 2.2.4  and python 3
Has anyone encountered this error? or any one help me with this error?
