### ISSUE TITLE
ValueError: GpuCorrMM images and kernel must have the same stack size

### ISSUE THREAD

**Issue by saugat** [flyyufelix/cnn_finetune#7]
I'm trying to retrain resnet_50 using my own datasets which is in  following shape:
('X_train: ', (11562L, 200L, 200L, 1L))
('X_valid:', (2891L, 200L, 200L, 1L))
('Y_train:', (11562L, 124L))
('Y_valid:', (2891L, 124L))

Once the model starts to do the training, it throws "GpuCorrMM images and kernel must have the same stack size".  More about the error is:

> Train on 11562 samples, validate on 2891 samples
Epoch 1/50
Traceback (most recent call last):
  File "resnet_50.py", line 195, in <module>
    validation_data=(X_valid, Y_valid))
  File "C:\Users\saugat_kc\AppData\Local\Continuum\Anaconda2\envs\resnet_env\lib\site-packages\keras\engine\training.py", line 1196, in fit
    initial_epoch=initial_epoch)
  File "C:\Users\saugat_kc\AppData\Local\Continuum\Anaconda2\envs\resnet_env\lib\site-packages\keras\engine\training.py", line 891, in _fit_loop
    outs = f(ins_batch)
  File "C:\Users\saugat_kc\AppData\Local\Continuum\Anaconda2\envs\resnet_env\lib\site-packages\keras\backend\theano_backend.py", line 959, in __call__
    return self.function(*inputs)
  File "C:\Users\saugat_kc\AppData\Local\Continuum\Anaconda2\envs\resnet_env\lib\site-packages\theano\compile\function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Users\saugat_kc\AppData\Local\Continuum\Anaconda2\envs\resnet_env\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Users\saugat_kc\AppData\Local\Continuum\Anaconda2\envs\resnet_env\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: GpuCorrMM images and kernel must have the same stack size

I'm using Python 2.7, Theano 0.9.0 with keras 1.2.2 on a Windows 10 platform.
Is there anything that I'm missing here?

**Comment by flyyufelix** [comment]
The dimension of your input does not comply with ResNet50. Input to your problem should be of the following dimension:

('X_train: ', (11562L, 3L, 200L, 200L))
('X_valid:', (2891L, 3L, 200L, 200L))
('Y_train:', (11562L, 124L))
('Y_valid:', (2891L, 124L))

The pre-trained CNN inputs must have 3 depth channels (color channels). For Theano, the depth dimension is placed in front of the spatial dimension.
